# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.1’
# Uncomment this line if you're using Swift
use_frameworks!

target 'NendVideoMediationAdapterSample' do
  pod 'NendSDK_iOS_CustomEventAdapter'
end

target 'NendVideoMediationAdapterSample_Swift' do
  pod 'NendSDK_iOS_CustomEventAdapter'
end
